allowBuilds:
  '@parcel/watcher': set this to true or false
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  '@swc/core': set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
  vue-demi: set this to true or false
minimumReleaseAgeExclude:
  - icu-minify@4.13.1
  - next-intl-swc-plugin-extractor@4.13.1
  - next-intl@4.13.1
  - use-intl@4.13.1
