DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS states CASCADE;
DROP TABLE IF EXISTS countries CASCADE;
DROP TABLE IF EXISTS desa CASCADE;
DROP TABLE IF EXISTS kecamatan CASCADE;

CREATE TABLE countries (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    iso3 char(3),
    numeric_code char(3),
    iso2 char(2),
    phone_code varchar(20),
    capital varchar(100),
    currency varchar(3),
    currency_symbol varchar(6),
    tld varchar(4),
    native varchar(100),
    region varchar(30),
    sub_region varchar(50),
    timezones text,
    translations text,
    default_format text,
    latitude numeric(10,8),
    longitude numeric(11,8),
    emoji varchar(30),
    emoji_u varchar(30),
    wiki_data_id varchar(10),
    notes varchar(255),
    inserted_at timestamptz DEFAULT now(),
    inserted_by varchar(100) DEFAULT 'System',
    updated_at timestamptz DEFAULT now(),
    updated_by varchar(100) DEFAULT 'System'
);

CREATE INDEX idx_countries_name
ON countries(name);

------------------------------------------------------------

CREATE TABLE states (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    country_id integer NOT NULL,
    country_code char(2) NOT NULL,
    fips_code varchar(8),
    iso2 varchar(6),
    latitude numeric(10,8),
    longitude numeric(11,8),
    wiki_data_id varchar(10),
    notes varchar(255),
    inserted_at timestamptz DEFAULT now(),
    inserted_by varchar(100) DEFAULT 'System',
    updated_at timestamptz DEFAULT now(),
    updated_by varchar(100) DEFAULT 'System',

    CONSTRAINT fk_states_country
        FOREIGN KEY (country_id)
        REFERENCES countries(id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_states_country
ON states(country_id);

CREATE INDEX idx_states_name
ON states(name);

------------------------------------------------------------

CREATE TABLE cities (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    state_id integer NOT NULL,
    state_code varchar(10) NOT NULL,
    country_id integer NOT NULL,
    country_code char(2) NOT NULL,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    wiki_data_id varchar(10),
    notes varchar(255),
    inserted_at timestamptz DEFAULT now(),
    inserted_by varchar(100) DEFAULT 'System',
    updated_at timestamptz DEFAULT now(),
    updated_by varchar(100) DEFAULT 'System',

    CONSTRAINT fk_cities_state
        FOREIGN KEY (state_id)
        REFERENCES states(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_cities_country
        FOREIGN KEY (country_id)
        REFERENCES countries(id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_cities_state
ON cities(state_id);

CREATE INDEX idx_cities_country
ON cities(country_id);

CREATE INDEX idx_cities_name
ON cities(name);

------------------------------------------------------------

CREATE TABLE kecamatan (
    id integer PRIMARY KEY,
    nama_kecamatan varchar(100),
    nama_alt varchar(100),
    id_kab_kota integer,
    id_provinsi integer,
    id_negara integer,
    inserted_at timestamptz DEFAULT now(),
    inserted_by varchar(100) DEFAULT 'System',
    updated_at timestamptz DEFAULT now(),
    updated_by varchar(100) DEFAULT 'System'
);

------------------------------------------------------------

CREATE TABLE desa (
    id bigint PRIMARY KEY,
    nama_desa_kelurahan varchar(100),
    nama_alt varchar(100),
    desa_kelurahan varchar(100),
    id_kecamatan integer,
    id_kab_kota integer,
    id_provinsi integer DEFAULT 102,
    id_negara integer DEFAULT 102,
    kode_pos varchar(100),
    inserted_at timestamptz DEFAULT now(),
    inserted_by varchar(100) DEFAULT 'System',
    updated_at timestamptz DEFAULT now(),
    updated_by varchar(100) DEFAULT 'System',

    CONSTRAINT fk_desa_kecamatan
        FOREIGN KEY (id_kecamatan)
        REFERENCES kecamatan(id)
        ON DELETE SET NULL
);